name: Repository Dispatch
on:
  repository_dispatch:
    types: myEvent

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
              
         # steps:
      - name: Assign client_payload to variable
        run: |
          CLIENT_PAYLOAD_JSON='${{ toJson(github.event.client_payload) }}'
          echo "Client Payload as JSON: $CLIENT_PAYLOAD_JSON"
          # You can now use $CLIENT_PAYLOAD_JSON in subsequent commands
          # For example, to parse a specific field using jq:
          NAME=$(echo "$CLIENT_PAYLOAD_JSON" | jq -r '.Name')
          echo "Name: $NAME"
          echo "$NAME=test" >> $GITHUB_ENV # Set environment variable
      - name: Try to access the variable from next Step
        run: |
          echo "Accessing name variable from previous step"
          echo  "The value is: ${{ env.NAME }}" 
          


