name: Repository Dispatch
on:
  repository_dispatch:
    types: myEvent

jobs:
  myEvent:
    runs-on: ubuntu-latest
    outputs:
          job_output_name: ${{ steps.my_step.outputs.my_output_variable }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
              
         # steps:
      - name: Assign client_payload to variable
        id: job1
        run: |
          CLIENT_PAYLOAD_JSON='${{ toJson(github.event.client_payload) }}'
          echo "Client Payload as JSON: $CLIENT_PAYLOAD_JSON"
          
          NAME=$(echo "$CLIENT_PAYLOAD_JSON" | jq -r '.Name')
          run: echo "SELECTED_COLOR=NAME" >> $GITHUB_OUTPUT
          echo "Name: $NAME"
          #run: echo "json_data=NAME" >> "$GITHUB_OUTPUT"
                    
      - name: Try to access the variable from next Step
        run: |
          echo "Accessing name variable from previous step"
          #echo "Output from job1: ${{ needs.job1.outputs.json_data }}"
          run: echo "The selected color is ${{ steps.job1.outputs.SELECTED_COLOR }}"
          
          


