name: Repository Dispatch
on:
  repository_dispatch:
    types: myEvent

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
              
         # steps:
      - name: Assign client_payload to variable
        run: |
          CLIENT_PAYLOAD_JSON='${{ toJson(github.event.client_payload) }}'
          echo "Client Payload as JSON: $CLIENT_PAYLOAD_JSON"
          # You can now use $CLIENT_PAYLOAD_JSON in subsequent commands
          # For example, to parse a specific field using jq:
          MY_FIELD=$(echo "$CLIENT_PAYLOAD_JSON" | jq -r '.Name')
          echo "My Field: $MY_FIELD"
          
      


