name: Repository Dispatch
on:
  repository_dispatch:
    types: myEvent
#jobs:
# myEvent:
#  runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.client_payload.ref }}
#      - run: echo "::set-output name=my_variable_1::${{ github.event.client_payload.key1 }}"

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo "::set-output name=my_variable_1::${{ github.event.client_payload.key1 }}"
          
      


